# Generated by Django 3.1.6 on 2021-02-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
