# Generated by Django 3.1.6 on 2021-02-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0005_auto_20210204_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
