# Generated by Django 3.1.6 on 2021-02-26 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0010_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='completed',
        ),
    ]
